/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32L1device.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


static void GPIO_Led_Config();
static void GPIO_ButtonInterruptConfig();
int main(void)
{
	GPIO_Led_Config();
	GPIO_ButtonInterruptConfig();
	GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_Pin_Set);

    /* Loop forever */
	while(1)
	{
		GPIO_TogglePin(GPIOA, GPIO_PIN_5);
	}
}

static void GPIO_Led_Config()
{
	GPIO_InitTypeDef_t GPIO_LedStruct = {0};

	RCC_GPIOA_CLOCK_ENABLE();
	GPIO_LedStruct.Mode = GPIO_MODE_OUT;
	GPIO_LedStruct.pinNumber = GPIO_PIN_5;
	GPIO_LedStruct.Speed = GPIO_SPEED_LOW;
	GPIO_LedStruct.Otype = GPIO_OTYPE_PUSH_PULL;

	GPIO_Init(GPIOA, &GPIO_LedStruct);
}
static void GPIO_ButtonInterruptConfig()
{
	EXTI_InitTypeDef_t EXTI_InitStruct = {0};
	RCC_SYSCFG_CLK_ENABLE();
	EXTI_LineConfig(EXTI_PORT_SOURCE_GPIOC, EXTI_LINE_SOURCE_4);
	EXTI_InitStruct.EXTI_LineCmd = ENABLE;
	EXTI_InitStruct.EXTI_LineNumber = EXTI_LINE_SOURCE_4;
	EXTI_InitStruct.EXTI_Mode = EXTI_MODE_INTERRUPT;
	EXTI_InitStruct.TriggerSelection = EXTI_TRIGGER_RISING;

	EXTI_Init(&EXTI_InitStruct);
	NVIC_EnableInterrupt(EXTI0_IRQNumber);
}
